version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:39"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 100
    commit-message:
      prefix: ""
      include: "scope"
    labels:
      - "dependencies"
