version: 2
updates:
  - package-ecosystem: npm
    directory: "src/"
    schedule:
      interval: "daily"
      time: "12:36"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 100
    ignore:
      - dependency-name: "*"
        update-type: "widen"
    commit-message:
      prefix: ""
      include: "scope"
    labels:
      - "dependencies"
