version: 2
updates:
  - package-ecosystem: npm
    directory: "src/"
    schedule:
      interval: "daily"
      time: "16:04"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "deps: "
      include: "scope"
    labels:
      - "dependencies"