version: 2
updates:
  - package-ecosystem: npm
    directory: "src/"
    schedule:
      interval: "daily"
      time: "17:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "chore(deps): "
      include: "scope"
    labels:
      - "dependencies"
