name: "Init Release Please"
on:
  - issues
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ReleasePlease
        run: "npm i release-please -g && release-please bootstrap --token=$GITHUB_TOKEN --repo-url=RedstonePfalz/Einkochen-leicht-gemacht"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}